### ISSUE TITLE
FNG neutron source choices

### ISSUE THREAD

**Issue by zxkjack123** [pshriwise/dag-openmc-cmp#10]
I prefer one of the following sources:
- Option 1: Iso-point source in the center of the geometry.
- Option 2: Iso-mesh source (cover the entire geometry)

@pshriwise  What's your opinion of the neutron source?

**Comment by pshriwise** [comment]
I think that covering the entire geometry would be a good idea. This will ensure that any geometric inconsistencies or weaknesses in the tracking algorithm are well explored whereas the iso-point source will limit the parts of the geometry that particles see.

**Comment by zxkjack123** [comment]
Decision: Option2: Iso-mesh source covers the entire geometry.
