### ISSUE TITLE
Compare the neutron flux of a mesh tally.

### ISSUE THREAD

**Issue by pshriwise** [pshriwise/dag-openmc-cmp#2]
- [x] : Read the neutron flux
- [x] : Plot the difference

**Comment by zxkjack123** [comment]
There are 80 voxels currently in the tally. It's tedious to compare every single voxel, and it's also hard to say whether they are close to each or not just by plotting them out. We should use a indicator to evaluate the difference between the two sets of results of the same mesh.

For a vector, we can use cosine similarity factor (range [-1, 1]) to evaluate the difference. Here, for mesh, it consists of many vectors. I propose to use distribution of the similarity factors as the major indicator for this comparison. How do you think about it?

**Comment by pshriwise** [comment]
Yeah I think that should be fine to start. The spectral results are nice to look at for the purpose of understanding why the differences might be occurring and the cosine comparison is a nice summary of the overall results.

**Comment by pshriwise** [comment]
After working out a few kinks, it's looking pretty good!
![n_flux_total](https://user-images.githubusercontent.com/4563941/58737124-001a5600-83c6-11e9-82be-51ba518c8261.png)
![similarity](https://user-images.githubusercontent.com/4563941/58737127-03154680-83c6-11e9-9311-8bf449c33039.png)
