### ISSUE TITLE
FNG model choices

### ISSUE THREAD

**Issue by zxkjack123** [pshriwise/dag-openmc-cmp#5]
This issue is used to discuss the choices of FNG models. 

There are several types of FNG models, we should use the model which will be easiest to ensure that data and materials are consistent between OpenMC and DAG-OpenMC.

**Comment by zxkjack123** [comment]
Some thoughts about the model:
1. We want a model with medium complexity, we don't need detectors. We can remove all detectors to make the model cleaner.

2. As we are going to use a psudo-source, we can remove all the neutron source part of the FNG model. It will be much eaiser for us to build the OpenMC model. 

By using these two simplicities, we can adapt the model based on FNG-dose model:
- delete all the detectors
- delete the neutron source part

@pshriwise How do you think about these changes?

**Comment by pshriwise** [comment]
Yeah that sounds like a good plan to me. I'd recommend looking at https://github.com/makeclean/csg2csg for converting the FNG-dose MCNP geometry to an OpenMC format.

**Comment by zxkjack123** [comment]
Csg2csg sounds to be a great tool, and we have an MCNP version of FNG-dose input file. And then we can use:
- mcnp2cad to create a CAD model
- csg2csg to create a OpenMC model

Then these two models should be consist with each other.  This means, we don't need to make any change to the MCNP model.

**Comment by pshriwise** [comment]
Excellent. Glad you're on board. We can look at the number of cells/volumes and the volumes of each to verify that the models have been converted correctly.

**Comment by zxkjack123** [comment]
So, next, we need to decide where to start. Which FNG-dose model are we going to use? I have an input file (looks like in MCNP 4) from SINBAD, but I am not sure this is a good one for our objective.

**Comment by pshriwise** [comment]
I think that one should be fine as long as it's compatible with a version of MCNP that we both have a license for.

**Comment by zxkjack123** [comment]
Do you have that file? I think we should check that our input files are exactly the same at the very beginning.
