### ISSUE TITLE
FNG model mcnp2cad conversion

### ISSUE THREAD

**Issue by zxkjack123** [pshriwise/dag-openmc-cmp#6]
I uploaded the `fng_dose` files from `SINBAD` in `fng_comp` branch. And then tried to convert `mcnp_n.inp` using `mcnp2cad` tool. However, I got the following error message:
```
Destroyed volume(s): 449
The 1 body did not have common part with the tool_body.
Destroyed volume(s): 450, 451
Intersection failed
LineExtractor out of lines, cannot takeLine().
```

I also tried several files got from Elliot, all of them have this error. I am not familiar with `mcnp2cad`, don't why this error happens. @pshriwise Do you have any idea of this error?

**Comment by pshriwise** [comment]
Did you see this error using the CLI version of `mcnp2cad` or was this in the Trelis plugin?

**Comment by zxkjack123** [comment]
In CLI version. I don't have a Trelis plugin version on hand, still finding it's install guides ...

**Comment by zxkjack123** [comment]
Problems related to geometry conversion have been solved. The file we should use as the origin of conversion is in branch `fng_comp`, `FNG/geometry/mcnp_n_adapted.inp`.

**Comment by zxkjack123** [comment]
FNG model converted form `mcnp2cad` is ready. In branch `fng_comp`, `FNG/geometry/dagmc.h5m`. Tested with a simple input. It runs without any error.
