### ISSUE TITLE
FNG DagOpenMC model overlap

### ISSUE THREAD

**Issue by zxkjack123** [pshriwise/dag-openmc-cmp#9]
I got the following error message when I tried: `openmc --geometry-debug -n 100` with the FNG DagOpenMC model:
```
Simulating batch 1
 ERROR: Overlapping cells detected: 6511, 6539 on universe 0
application called MPI_Abort(MPI_COMM_WORLD, -1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=-1
:
system msg for write_line failure : Bad file descriptor
 ERROR: Overlapping cells detected: 6559, 6024 on universe 0
application called MPI_Abort(MPI_COMM_WORLD, -1) - process 0
```

@pshriwise Any idea to get rid of this error?

**Comment by zxkjack123** [comment]
I tested with other DAGMC files I used before, found that every model has been detected with this error. For example, the following is the error message of a simple 4-box model:
```
Simulating batch 1
 ERROR: Overlapping cells detected: 2, 7 on universe 0
application called MPI_Abort(MPI_COMM_WORLD, -1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=-1
:
system msg for write_line failure : Bad file descriptor
Segmentation fault (core dumped)
```

**Comment by pshriwise** [comment]
Oh interesting! Let's look into that. It might be that our `point_in_volume` case isn't terribly robust for points on the boundary or points in the implicit complement where rays miss the geometry entirely.

**Comment by pshriwise** [comment]
This is indeed a `point_in_volume` problem. At this point we know it doesn't have an effect on results and we're aiming to address it in DAGMC soon.
